name: PR Title Check

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  check-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title against Conventional Commits
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          validateSingleCommit: false
          wip: true
          subjectPattern: '^(feat|fix|docs|refactor|perf|test|chore)(\([a-z0-9\-]+\))?: .+$'
          subjectPatternError: >
            Title must match <type>(scope): description
            Example: 'feat(auth): add login'
          types: |
            feat
            fix
            docs
            refactor
            perf
            test
            chore
          requireScope: false
